//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KB.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_KB_Article
    {
        public int Id { get; set; }
        public string Body { get; set; }
        public string CustomURL { get; set; }
        public int CategoryId { get; set; }
        public bool IfFeatured { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public short Status { get; set; }
        public string Title { get; set; }
        public Nullable<int> Views { get; set; }
        public string Name { get; set; }
        public Nullable<int> Index { get; set; }
    }
}
